### ISSUE TITLE
Need a method to inject gems into the gemfile before the test_app_generator

### ISSUE THREAD

**Issue by jcoyne** [cbeer/engine_cart#19]
The branch of sufia I'm on depends on an unreleased version of active-fedora (8.0.0.alpha) and this is listed in its sufia.gemspec.

When I run rake engine_cart:generate it fails before running the generator because it can't find a version of active-fedora that meets this spec.

I've added this to my Rakefile to work around it:

```ruby
EXTRA_GEMS =<<EOF
gem 'active-fedora', github: 'projecthydra/active_fedora', branch: 'fedora-4'
gem 'hydra-head', github: 'projecthydra/hydra-head', branch: 'fedora-4'
gem 'hydra-collections', github: 'projecthydra/hydra-collections', branch: 'fedora-4'

EOF

namespace :engine_cart do
  # we're adding some extra stuff into the gemfile beyond what engine_cart gives us by default
  task :inject_gemfile_extras do
    open(File.expand_path('Gemfile', EngineCart.destination), 'a') do |f|
      f.write EXTRA_GEMS
    end
  end
end

```

But I wonder if that wouldn't better be handled by re-introducing Gemfile.extra?

Another way to work around this is by putting the github gems in Gemfile and running `bundle exec rake engine_cart:generate`

**Comment by ndushay** [comment]
I have a similar problem in needing an unreleased version of a gem;  the test app uses the released version of the gem.  :-(

**Comment by cbeer** [comment]
I think Gemfile.extra was reintroduced, no?

**Comment by cbeer** [comment]
e.g. https://github.com/sul-dlss/spotlight/blob/master/spec/test_app_templates/Gemfile.extra

**Comment by jcoyne** [comment]
@cbeer Gemfile.extra is only included on the generated applications Gemfile. The gems are needed before that happens.

**Comment by jcoyne** [comment]
See https://travis-ci.org/projecthydra/sufia/jobs/61206708

**Comment by cbeer** [comment]
Try adding this to your Gemfile:

```ruby
eval_gemfile File.expand_path("spec/test_app_templates/Gemfile.extra", File.dirname(__FILE__))
```
