### ISSUE TITLE
Accommodate environments where gems are vendorized.

### ISSUE THREAD

**Issue by grosscol** [cbeer/engine_cart#25]
engine_cart does not support development environments where gems are all contained within the project and users are not permitted to install gems at the system level.

Setting up a project using `bundle install --path` puts all the gems in vendor/path.  The usage of engine_cart becomes `bundle exec rake engine_cart:generate`.  The Bundle.clean_env usage and system calls to rails directly breaks in this setup.

It should be possible to make the calls agnostic to being run from within or without a bundled environment to start.  So `bundle exec rake engine_cart:generate` and `rake engine_cart:generate` should both function as expected.

**Comment by cbeer** [comment]
Fixed by 6989482c34b13777bb71671515491ddc2e56d0d4?
