### ISSUE TITLE
Issue with travis caching and ruby 2.2.1-3

### ISSUE THREAD

**Issue by jcoyne** [cbeer/engine_cart#28]
Seems to work okay if I turn off caching or use ruby 2.2.0

```
Errno::ENOENT: No such file or directory @ sys_fail2 - (/tmp/d20150918-4121-3d593j/internal, ./spec/internal)

/home/travis/build/projecthydra/hydra-editor/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.7.1/lib/engine_cart/tasks/engine_cart.rake:45:in `block (3 levels) in <top (required)>'

/home/travis/build/projecthydra/hydra-editor/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.7.1/lib/engine_cart/tasks/engine_cart.rake:29:in `block (2 levels) in <top (required)>'

/home/travis/build/projecthydra/hydra-editor/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.7.1/lib/engine_cart/tasks/engine_cart.rake:85:in `block (2 levels) in <top (required)>'

/home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'

/home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

Tasks: TOP => engine_cart:create_test_rails_app
```

**Comment by jcoyne** [comment]
Related to https://github.com/travis-ci/travis-ci/issues/4822

**Comment by atz** [comment]
`FileUtils.move` should be consistently reliable on all modern rubies including the line in question:
https://github.com/cbeer/engine_cart/blob/570830c1ed08505b1e851d01917d82d85074342e/lib/engine_cart/tasks/engine_cart.rake#L45

It has seemingly nothing to do with ruby version or bundler caching.  Either we have a generated rails app dir to move or we don't.  The error says we don't.  I thereby conclude that the preceeding `rails new` call is failing in some unanticipated way, where bundler caching seems plausibly in play.  

We should check for the `internal` dir having been created and abort if missing.  Instead, we check `$?`, which is meaningless in this context.  Example via `irb`:

```ruby
2.2.0 :001 > `bullshit`
Errno::ENOENT: No such file or directory - bullshit
	from (irb):1:in ``'
	from (irb):1
	from /Users/atz/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :002 > $?
 => #<Process::Status: pid 17660 exit 127> 
2.2.0 :003 > puts "abort?" unless $?
 => nil 
2.2.0 :004 > puts "abort!" unless $?.success?
abort!
```

We probably want `$?.success?`, though I would also explicitly check for the newly created directory.

This only defers the more material question: `rails new`, Y U NO WORK?  Would really help to have the output/stderr in our build log and not swallowed by backticks, ideally bracketed by:
```ruby
puts "travis_fold:start:enginecart-rails-new\r" if ENV['TRAVIS'] == 'true'
...
puts "travis_fold:end:enginecart-rails-new\r" if ENV['TRAVIS'] == 'true'
```
Then it auto-collapses in Travis.
