### ISSUE TITLE
No hook for db:seed

### ISSUE THREAD

**Issue by atz** [cbeer/engine_cart#51]
We can copy migrations during the callback to `MyApp::InstallGenerator`, but we don't have a hook to make use of `db:seed` to populate the schema with initial values.  We cannot run them in the InstallGenerator because without running `db:migrate` first, which is already otherwise being called by EngineCart after the generator.  

What's the best move?  Call migrate explicitly and end up calling migrate twice?

**Comment by cbeer** [comment]
Running `db:migrate` twice sounds like a fine workaround.
